#+TITLE: Tavern ~ Elixir + Emacs 
AUTHOR: MinasMazar
#+DATE: <2023-12-29 Fri>
#+PROPERTY: header-args :tangle ~/.emacs.d/modules/tavern.el :mkdirp yes
#+STARTUP: show2levels

* What is Tavern?

[[https://github.com/MinasMazar/tavern][Tavern is an Elixir project]] that allow to inject some Elisp code in a running instance of [[https://www.gnu.org/software/emacs/][Emacs]] (using the =emacsclient= executable) and to easily write Emacs lisp source code using plain Elixir terms.

* Why I should use it?

No particular reason; if you ðŸ’œï¸ developing with the [[https://elixir-lang.org/][Elxir programming language]] and you â™¥ï¸ =Emacs=, you should enjoy experimenting with it.

* Elixir => Elisp

The =Tavern.Elisp= module implement the =sexp= function that keeps an Elixir term and translates it to a string containing the equivalent Elisp code. Keep an eye to [[https://github.com/MinasMazar/tavern/blob/master/lib/tavern/elisp.ex][the module documentation]] for more details.

* Installation
** Requirements

- you've Elixir installed in your system (ref the [[https://elixir-lang.org/install.html][doc]])
- you've an [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Invoking-emacsclient.html][emacsclient]] executable installed in your system

** Install

#+begin_src sh
  git clone https://github.com/MinasMazar/tavern.git
  cd tavern
  mix deps.get
  mix compile
#+end_src

** Usage
*** Livebook

The [[https://github.com/MinasMazar/tavern/blob/master/tavern.livemd][Tavern livebook]] show you some ideas on how to improve your Emacs experience using the Elixir. [[https://livebook.dev/][For more information about Livebook, check the website]].

*** Examples

Or you can run /bot/ of in [[https://github.com/MinasMazar/tavern/tree/master/examples][the examples directory]].

#+begin_src sh
mix run examples/bot.exs
#+end_src
